# Generated by Django 5.1.10 on 2025-08-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0057_annotation_proj_result_octlen_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklock",
            name="assigned_by",
            field=models.ForeignKey(
                help_text="User who assigned this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_task_locks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
