# Generated by Django 5.1.10 on 2025-08-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MAINTAINER", "Maintainer"),
                    ("SUPERVISOR", "Supervisor"),
                    ("WORKER", "Worker"),
                ],
                db_index=True,
                default="WORKER",
                help_text="Organization-specific role for this member",
                max_length=16,
                verbose_name="organization role",
            ),
        ),
    ]
